modality: "text-image"
num_classes: 2
batch_size: 32
learning_rate: 1.0e-4
num_epochs: 10
dropout_p: 0.1
text_embedder: "all-mpnet-base-v2"
dialogue_summarization_model: "sshleifer/distilbart-cnn-12-6"
trained_model_version: "version_106"
trained_model_path: null
gpus: [0, 1]
train_data_path: "./data/multimodal_train_10000.tsv"
test_data_path: "./data/multimodal_test_1000.tsv"
preprocessed_train_dataframe_path: "./data/train__text_image_dataframe.pkl"
preprocessed_test_dataframe_path: "./data/test__text_image_dataframe.pkl"
